### ISSUE TITLE
there is no request send

### ISSUE THREAD

**Issue by mustafa2021** [Quitten/doser.py#1]
it dosn't send any request

**Comment by Quitten** [comment]
Can you give an example command? in addition, try to git pull and check now, i just pushed a new version fix some issues.

**Comment by mustafa2021** [comment]
there is a new error 
Traceback (most recent call last):
 File "doser.py" , line , in <module>
import requests
ImportError: no module named requests

**Comment by Quitten** [comment]
you just need to install requests module:
pip install requests
