### ISSUE TITLE
Small Syntax-Error and request

### ISSUE THREAD

**Issue by FinnKr** [Quitten/doser.py#5]
I think it needs to be "printMsg" rather than "printedMsg" in Line 65:
https://github.com/Quitten/doser.py/blob/55dbd3072f466c89c8b1d61ac9b761da47389ee8/doser.py#L65

And is there any way to stop this other than force-closing the terminal?

**Comment by Quitten** [comment]
Fixed in 4abdebb3bcf8445d0512ab4205574196744a339b.
The project is currently deprecated, I want to re-write it in golang for better performance
